### ISSUE TITLE
Plasma crash when click on widget

### ISSUE THREAD

**Issue by Fisiu** [plasma-light/plasma-widget-radio#8]
I build rpm package for openSUSE, after installing it and adding a widget to panel, when I click on widget → plasma crashes:
```c++
Thread 1 (Thread 0x7f370bdf5900 (LWP 2189)):
[KCrash Handler]
#6  libvlc_set_user_agent (p_i=0x0, name=0x7f364df6570b "RadioPlayer Widget 0.1", http=0x7f364df656fb "RadioPlayer/0.1") at core.c:139
#7  0x00007f364df64771 in RadioPlayer::RadioPlayer (this=0x4317bc0) at /usr/src/debug/plasma-widget-radiotray/plugin/radioplayer.cpp:37
#8  0x00007f364df633ee in QQmlPrivate::QQmlElement<RadioPlayer>::QQmlElement (this=0x4317bc0) at /usr/include/qt5/QtQml/qqmlprivate.h:93
#9  QQmlPrivate::createInto<RadioPlayer> (memory=0x4317bc0) at /usr/include/qt5/QtQml/qqmlprivate.h:102
#10 0x00007f3708e7e6e9 in QQmlType::create (this=this@entry=0x7f36dc096440) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlmetatype.cpp:740
#11 0x00007f3708ede4c2 in QQmlObjectCreator::createInstance (this=this@entry=0x7fffd77cf910, index=3, parent=0x43166b0, isContextObject=isContextObject@entry=false) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlobjectcreator.cpp:1046
#12 0x00007f3708edf9e4 in QQmlObjectCreator::setPropertyBinding (this=this@entry=0x7fffd77cf910, property=0x7f36dc014310, binding=binding@entry=0x7f36dc0c28b4) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlobjectcreator.cpp:743
#13 0x00007f3708ee05e6 in QQmlObjectCreator::setupBindings (this=this@entry=0x7fffd77cf910, bindingsToSkip=...) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlobjectcreator.cpp:695
#14 0x00007f3708edd806 in QQmlObjectCreator::populateInstance (this=this@entry=0x7fffd77cf910, index=-1, instance=0x0, instance@entry=0x43166b0, bindingTarget=0x2678a50, bindingTarget@entry=0x43166b0, valueTypeProperty=valueTypeProperty@entry=0x0, bindingsToSkip=...) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlobjectcreator.cpp:1320
#15 0x00007f3708ede1aa in QQmlObjectCreator::createInstance (this=this@entry=0x7fffd77cf910, index=index@entry=0, parent=parent@entry=0x0, isContextObject=isContextObject@entry=true) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlobjectcreator.cpp:1167
#16 0x00007f3708edeafb in QQmlObjectCreator::create (this=this@entry=0x7fffd77cf910, subComponentIndex=subComponentIndex@entry=-1, parent=parent@entry=0x0, interrupt=interrupt@entry=0x0) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlobjectcreator.cpp:197
#17 0x00007f3708ede766 in QQmlObjectCreator::createInstance (this=this@entry=0x430c800, index=index@entry=3, parent=parent@entry=0x0, isContextObject=isContextObject@entry=true) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlobjectcreator.cpp:1076
#18 0x00007f3708edeafb in QQmlObjectCreator::create (this=0x430c800, subComponentIndex=6, parent=parent@entry=0x0, interrupt=interrupt@entry=0x7fffd77cfba0) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlobjectcreator.cpp:197
#19 0x00007f3708e6e28f in QQmlIncubatorPrivate::incubate (this=0x430c730, i=...) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlincubator.cpp:302
#20 0x00007f3708e6eade in QQmlIncubationController::incubateFor (this=this@entry=0x276a590, msecs=<optimized out>) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlincubator.cpp:395
#21 0x00007f3709f5e38c in KDeclarative::QmlObjectIncubationController::incubate (this=0x276a580) at /usr/src/debug/kdeclarative-5.26.0/src/kdeclarative/private/qmlobject_p.h:63
#22 KDeclarative::QmlObjectIncubationController::incubatingObjectCountChanged (this=0x276a580, count=1) at /usr/src/debug/kdeclarative-5.26.0/src/kdeclarative/private/qmlobject_p.h:79
#23 0x00007f3708e6e78a in QQmlEnginePrivate::incubate (this=this@entry=0x2678a50, i=..., forContext=forContext@entry=0x295dd10) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlincubator.cpp:97
#24 0x00007f3708e69d86 in QQmlComponent::create (this=this@entry=0x29ed180, incubator=..., context=<optimized out>, forContext=forContext@entry=0x0) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlcomponent.cpp:1059
#25 0x00007f3709f5acf0 in KDeclarative::QmlObject::createObjectFromComponent (this=0x289cce0, component=0x29ed180, context=0x2923810, initialProperties=...) at /usr/src/debug/kdeclarative-5.26.0/src/kdeclarative/qmlobject.cpp:349
#26 0x00007f370b7e5db9 in PlasmaQuick::AppletQuickItemPrivate::createFullRepresentationItem (this=0x289f640) at /usr/src/debug/plasma-framework-5.27.0~20160928~b115ea1.git/src/plasmaquick/appletquickitem.cpp:208
#27 0x00007f370b7e62e5 in PlasmaQuick::AppletQuickItem::setExpanded (this=0x28dbcb0, expanded=<optimized out>) at /usr/src/debug/plasma-framework-5.27.0~20160928~b115ea1.git/src/plasmaquick/appletquickitem.cpp:713
#28 0x00007f370b7e681e in PlasmaQuick::AppletQuickItem::qt_static_metacall (_o=_o@entry=0x28dbcb0, _c=_c@entry=QMetaObject::WriteProperty, _id=_id@entry=7, _a=_a@entry=0x7fffd77cff80) at /usr/src/debug/plasma-framework-5.27.0~20160928~b115ea1.git/build/src/plasmaquick/moc_appletquickitem.cpp:328
#29 0x00007f370b7e94db in PlasmaQuick::AppletQuickItem::qt_metacall (this=this@entry=0x28dbcb0, _c=_c@entry=QMetaObject::WriteProperty, _id=7, _a=_a@entry=0x7fffd77cff80) at /usr/src/debug/plasma-framework-5.27.0~20160928~b115ea1.git/build/src/plasmaquick/moc_appletquickitem.cpp:373
#30 0x00007f36ec04ecd5 in AppletInterface::qt_metacall (this=0x28dbcb0, _c=QMetaObject::WriteProperty, _id=<optimized out>, _a=0x7fffd77cff80) at /usr/src/debug/plasma-framework-5.27.0~20160928~b115ea1.git/build/src/scriptengines/qml/moc_appletinterface.cpp:661
#31 0x00007f3708e671de in QQmlPropertyPrivate::write (object=object@entry=0x28dbcb0, property=..., value=..., context=0x2b9d780, flags=...) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/qml/qqmlproperty.cpp:1252
#32 0x00007f3708e2e216 in QV4::QObjectWrapper::setProperty (engine=engine@entry=0x26862a0, object=object@entry=0x28dbcb0, property=0x7f36dc0e39a0, value=...) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/jsruntime/qv4qobjectwrapper.cpp:538
#33 0x00007f3708e2e82f in QV4::QObjectWrapper::setQmlProperty (engine=engine@entry=0x26862a0, qmlContext=0x2b9d780, object=0x28dbcb0, name=name@entry=0x7f36e70003d8, revisionMode=revisionMode@entry=QV4::QObjectWrapper::IgnoreRevision, value=...) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/jsruntime/qv4qobjectwrapper.cpp:425
#34 0x00007f3708e2e94d in QV4::QObjectWrapper::put (m=0x7f36e70003e0, name=0x7f36e70003d8, value=...) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/jsruntime/qv4qobjectwrapper.cpp:695
#35 0x00007f3708e3f1f6 in QV4::Object::put (v=..., name=<optimized out>, this=<optimized out>) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/jsruntime/qv4object_p.h:302
#36 QV4::Runtime::setProperty (engine=0x26862a0, object=..., nameIndex=<optimized out>, value=...) at /usr/src/debug/qtdeclarative-opensource-src-5.6.1/src/qml/jsruntime/qv4runtime.cpp:571
#37 0x00007f370bd4f10c in ?? ()
#38 0x0000000000000000 in ?? ()
```

**Comment by azubieta** [comment]
Would you please specify which version of plasma, KF5 and VLC do you use?

**Comment by Fisiu** [comment]
Plasma Shell: 5.8.3
KDE Frameworks: 5.26.0
libvlc: 3.0.0-git9358

It seems radiotray requires vlc, not only libvlc. vlc was missing in my system, but after installing it radiotray works.

PS. Is there a way to make radiotray work with vlc 2.2.X?

**Comment by star-buck** [comment]
The goal should be to make it an independent app, so it ships its own
(copied, but selfcontained) libs and parts.

**Comment by Fisiu** [comment]
Sound good :+1: 

In the meantime I'm going to update package for openSUSE to require vlc 3.
